feat: add helsinki-benefit amount estimate calculator
City-of-Helsinki/drupal-hdbt pull request #1045
Opened 2024-08-29 09:13 UTC by sirtawast

# [HL-360](https://helsinkisolutionoffice.atlassian.net/browse/HL-360) / [UHF-10588](https://helsinkisolutionoffice.atlassian.net/browse/UHF-10588)

## What was done

* Implement a new calculator for https://www.hel.fi/fi/yritykset-ja-tyo/tyonantajat/taloudelliset-tuet/helsinki-lisa-tyonantajille
* Write tests for the new calculator

## How to install

* `npm install`
* optionally, install test dependencies `cd src/js/calculator/helsinki_benefit_amount_estimate/tests && npm install`

## How to test

### To run manual tests

* `npm run build`
* start a local server on `drupal-hdbt/`, for instance `python -m http.server 3001`
* open http://localhost:3001/src/js/calculator/helsinki_benefit_amount_estimate/helsinki-benefit-test.html on your browser

### To run automatic browser tests

This requires test dependencies to be installed

* `cd src/js/calculator/helsinki_benefit_amount_estimate/tests && npm run test`

## Continuous documentation

* [x] This feature has been documented/the documentation has been updated
* [ ] This change doesn't require updates to the documentation

https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HEL/pages/8963751960/Helsinki-lis+n+m+r+n+laskuri

## Translations

* [x] Translations have been added to .js -files and included in this PR

---

## Screenshot 📸 🖼️ 
 
![screencapture-localhost-3001-src-js-calculator-helsinki-benefit-amount-estimate-helsinki-benefit-test-html-2024-08-29-12_20_08](https://github.com/user-attachments/assets/acbe484d-7d5c-4306-b14a-661ea3c30de0)

[HL-360]: https://helsinkisolutionoffice.atlassian.net/browse/HL-360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UHF-10588]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-10-03 08:48 UTC, teroelonen requested changes
This is really nicely done and the tests were a good addition. We should definitely consider adding those ourselves! What I would still ask for you to do is to check my comments on the commented lines if they are still needed and to add the calculator machine name to `templates/paragraphs/paragraph--calculator.html.twig` file on line 32. Also this needs to have the minified js added and committed under the dist folder so please add that as well and we can merge this one 🙏

2024-10-03 08:48 UTC, teroelonen commented on src/js/calculator/helsinki_benefit_amount_estimate/_form.js
> +          // value: 2000, // TODO: remove after debug
I am guessing these can be removed :)

2024-10-03 08:48 UTC, teroelonen commented on src/js/calculator/helsinki_benefit_amount_estimate/_form.js
> +      //     helper_text: t('other_expenses_helper_text'),
Should this still be kept here in case it is needed in the future?

2024-10-03 08:48 UTC, teroelonen commented on src/js/calculator/helsinki_benefit_amount_estimate/_translations.js
> +*/
These comments can be removed.

2024-10-07 06:54 UTC, sirtawast commented
> This is really nicely done and the tests were a good addition. We should definitely consider adding those ourselves! What I would still ask for you to do is to check my comments on the commented lines if they are still needed and to add the calculator machine name to `templates/paragraphs/paragraph--calculator.html.twig` file on line 32. Also this needs to have the minified js added and committed under the dist folder so please add that as well and we can merge this one 🙏

Job's done 👍

2024-10-07 10:57 UTC, teroelonen approved these changes
This is very good now 🦖

2024-10-07 10:58 UTC, merged