UHF-4528: Add template for minimal display on TPR-units
City-of-Helsinki/drupal-hdbt pull request #270
Opened 2022-03-22 10:45 UTC by teroelonen

# TASKNAME [UHF-0000](https://helsinkisolutionoffice.atlassian.net/browse/UHF-0000)
A longer description of the task

## What was done
* Describe what was done

## How to install
* Make sure your instance is up and running on latest dev branch.
    * `git pull origin dev`
    * `make fresh`
* Update the HDBT theme
    * `composer require drupal/hdbt:dev-UHF-0000_insert_correct_branch`
* Run `make drush-cr`

## How to test
* Describe how to test the feature

## Other PRs
*

2022-04-01 10:28 UTC, tapsal approved these changes
Great! 🚀

2022-04-01 11:04 UTC, Arkkimaagi requested changes

2022-04-01 12:50 UTC, teroelonen commented on templates/module/helfi_tpr/tpr-unit.html.twig
> +          <h3 class="unit__title">
We don't - changed it to default to h3 and if you decide to use this display outside a component container (that has title that defaults to h2) which we haven't done so far you need to extend this template and give it some other level heading element. Refactored the teaser to have the same.

2022-04-01 12:51 UTC, teroelonen commented on src/scss/06_components/paragraphs/_unit-search.scss
> +  .views-row {
Yeah can be on single row. Just a mistake - had some other stuff under it before and forgot to remove nesting after it became redundant.

2022-04-01 12:53 UTC, teroelonen commented on src/scss/06_components/paragraphs/_unit-search.scss
> +      margin-top: -$spacing-and-half * 0.5;
Hahahaha I sure agree - this was copied from your code so I thought maybe you don't want me to write 12 here but calculate it from the the line height of the body. Changed to -12px and added a comment.

2022-04-01 12:54 UTC, teroelonen commented on src/scss/06_components/pages/_unit.scss
> +  &:hover {
Added and changed the style to apply to correct place - the link and not the surrounding element.

2022-04-01 12:56 UTC, teroelonen commented on src/scss/06_components/pages/_unit.scss
> +      width: calc(100% - (#{$spacing-double} + #{$spacing-and-half}));
Parenthesis never hurt anyone!! :D It was my motto in math at school so maybe thats why I used them there. Anyway removed them if they made it less readable.

2022-04-04 08:09 UTC, Arkkimaagi approved these changes
Code looks good to go!

2022-04-04 08:23 UTC, merged