WiP: Run PHPCS on git commit
City-of-Helsinki/drupal-hdbt pull request #440
Opened 2022-10-11 06:58 UTC by khalima

# Run PHPCS on git commit.

## What was done

* Added shell script to the theme pre-commit hook

## How to install

* Make sure your instance is up and running on latest dev branch.
  * `git pull origin dev`
  * `make fresh`
* Update the HDBT theme
  * `composer require drupal/hdbt:dev-UHF-X_phpcs_run_on_commit`
* Run `make drush-cr`

## How to test

* [ ] Check that this feature works
* [ ] Check that code follows our standards

## Designers review

* [ ] This PR does not need designers review
* [ ] This PR has been visually reviewed by a designer (Name of the designer)

## Other PRs

* Link to other PR

2023-01-25 08:39 UTC, Arkkimaagi requested changes
Left a couple of notes for when you get back to this.

2023-01-25 08:39 UTC, Arkkimaagi commented on .nvmrc
> +16.18.0
This is outdated

2023-01-25 08:39 UTC, Arkkimaagi commented on .husky/pre-commit
> +if [[ "$DIR" == *"/public/themes/contrib/"* ]]; then
Maybe we should check if the tools are available from Drupal before continuing to use them?

2024-04-15 06:11 UTC, khalima commented
Closing this as running phpcs manually on local env should be enough.

2024-04-15 06:11 UTC, closed without merging