Uhf 0000 embedded content cookie blocker lang fixes
City-of-Helsinki/drupal-hdbt pull request #612
Opened 2023-03-30 11:21 UTC by dire

# UHF-0000

The embedded content blocker doesn't need to support RTL languages as it's displayed in English.

## What was done

* Removed the RTL support and added `dir` and `lang` attributes.

## How to install

* Make sure your etusivu instance is up and running on latest dev branch.
  * `git pull origin dev`
  * `make fresh`
* Update the HDBT theme
  * `composer require drupal/hdbt:dev-UHF-0000_embedded_content-cookie-blocker-lang-fixes`
* Run `npm run build` inside hdbt theme.
* Run `make drush-cr`

## How to test

* [ ] Check that the cookie content blocker over remote videos or maps follows LTR and has English language attribute and `dir=ltr` on all languages except fi, sv and en.

2023-03-31 08:07 UTC, dire commented
I added part of UHF-8089 changes to this one as those changes needed something that is added in this PR.

2023-03-31 10:18 UTC, Arkkimaagi requested changes
I was able to do only a partial review as to me it seems that this does not work at all.
![image](https://user-images.githubusercontent.com/1191667/229093772-b0560ecc-ad85-4baa-a6fe-e737e8b9bcaf.png)

2023-03-31 13:09 UTC, dire commented
External map link has been wrapped now with the `lang` and `dir` attributes.

2023-04-03 05:22 UTC, Arkkimaagi approved these changes
Seems to work as it should. Good job! Approved 🌹

2023-04-03 05:32 UTC, merged