Uhf 8529 childcare calculator text updates
City-of-Helsinki/drupal-hdbt pull request #672
Opened 2023-05-25 11:39 UTC by Arkkimaagi

# [UHF-8529](https://helsinkisolutionoffice.atlassian.net/browse/UHF-8529)

* We have some text and translation updates for "Early childhood education fee calculator"
    * Ingress updates
    * Translation file updates
    * Sibling discount as new detail to the receipt

## What was done

* [Demo environment](https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HEL/pages/8189902851/Demo-ymp+rist+n+k+ytt) was updated with new ingress in three languages
* Translation file was verified and updated
* Sibling discount feature was added

## How to install

* Make sure your KASKO instance is up and running on latest dev branch.
  * `git pull origin dev`
  * `make fresh`
* Update the HDBT theme
  * `composer require drupal/hdbt:dev-UHF-8529_childcare_calculator_text_updates`
* Run `make drush-cr`
* Add a page with the early childhood calculator.

## How to test

* [ ] Check that texts match what the JIRA issue describes
* [ ] Check that [demo site](https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HEL/pages/8189902851/Demo-ymp+rist+n+k+ytt) ingress texts match what the JIRA issue describes
* [ ] Check that code follows our standards

## Designers review

* [X] This PR does not need designers review

2023-05-25 14:17 UTC, teroelonen commented
The full-time texts are a bit strange. There shouldn't be so much space there between the dash I think.
<img width="572" alt="Screenshot 2023-05-25 at 17 16 25" src="https://github.com/City-of-Helsinki/drupal-hdbt/assets/2276077/cc333ac6-bdeb-4358-aace-970b3010c1e5">

2023-05-25 14:19 UTC, teroelonen commented
Also for the second child there is slightly different spacing. 
<img width="927" alt="Screenshot 2023-05-25 at 17 18 09" src="https://github.com/City-of-Helsinki/drupal-hdbt/assets/2276077/0eb3ada3-5b08-4ba3-8844-a7246e99859a">

2023-05-25 14:24 UTC, teroelonen requested changes
Check the comments - otherwise works very nicely!

2023-05-25 14:24 UTC, teroelonen commented on src/js/calculator/early_childhood_education_fee/_translations.js
> +    en: 'Sibling discount, ${discount} % of the full- time fee for the youngest child.',
Fix the full-time here.

2023-05-26 06:04 UTC, Arkkimaagi commented on src/js/calculator/early_childhood_education_fee/_translations.js
> +    en: 'Sibling discount, ${discount} % of the full- time fee for the youngest child.',
Good catch! Fixed now!

2023-05-26 06:04 UTC, Arkkimaagi commented on src/js/calculator/early_childhood_education_fee/_translations.js
> +    en: 'Sibling discount, ${discount} % of the full - time fee for the youngest child.',
Good catch! Fixed now!

2023-05-26 06:09 UTC, teroelonen approved these changes
This works nicely, great job!! 🦖

2023-05-26 06:09 UTC, merged