added cacheing for config
City-of-Helsinki/drupal-hdbt pull request #696
Opened 2023-06-20 10:57 UTC by oviag

Issue: https://helsinkisolutionoffice.atlassian.net/browse/PLAENH-940

Added cacheing for config as we observed from profiling that the function is called numerous times.

2023-06-21 14:30 UTC, dragos-dumi-ibm approved these changes
looks fine

2023-06-22 07:49 UTC, tuutti requested changes

2023-06-22 07:49 UTC, tuutti commented on hdbt.theme
> +  $site_info = &drupal_static(__FUNCTION__);
Most of these are statically cached already, like config storage and language negotiation, but if we want to do it anyways then we probably should cache everything, like:

```php
function _hdbt_set_site_information(array &$variables) : void {
  static $values = [];

  if (!$values) {
    $language_id = \Drupal::languageManager()->getCurrentLanguage(LanguageInterface::TYPE_CONTENT)->getId();

    // Set site_name as variable.
    $site_config = \Drupal::config('system.site');
    $values['site_name'] = $site_config->get('name');

    $values['city_name'] = t('City of Helsinki');

    // Set site front page absolute url as variable.
    $values['site_front_url'] = Url::fromRoute('<front>', [], ['absolute' => TRUE]);

    /** @var \Drupal\helfi_api_base\Environment\EnvironmentResolver $resolver */
    $resolver = \Drupal::service('helfi_api_base.environment_resolver');

    // Return if the current project is not in environments list.
    try {
      $activeEnvironment = $resolver->getActiveEnvironment()->getEnvironmentName();
      $environment = $resolver->getEnvironment(Project::ETUSIVU, $activeEnvironment);
    }
    catch (\Exception $e) {
      // Set Etusivu absolute url as variable.
      $values['frontpage_instance_url'] = Url::fromUri("https://www.hel.fi/$language_id/");
      return;
    }

    // Revert to English path, if current language path is not found.
    try {
      $url = $environment->getUrl($language_id);
    }
    catch (\Exception $e) {
      $url = $environment->getUrl('en');
    }

    // Set Etusivu absolute url as variable.
    $values['frontpage_instance_url'] = Url::fromUri($url);
  }
  $variables += $values;
}
```

2023-06-22 10:50 UTC, tuutti approved these changes
I didn't actually test this, but looks good otherwise

2023-06-22 10:54 UTC, oviag commented
> I didn't actually test this, but looks good otherwise

I did test it, and didn't find any flaws, works the same.

2023-06-22 13:40 UTC, merged