UHF-8737 hdbt.module cleanup
City-of-Helsinki/drupal-hdbt pull request #714
Opened 2023-07-24 13:40 UTC by rpnykanen

### What was done
- Created bundle entities in order to get rid of code in .theme file

### How to install

* Make sure your instance is up and running on latest dev branch.
  * git pull origin dev
  * make fresh
* Update the HDBT theme
  * composer require drupal/hdbt:dev-UHF-8737_theme_cleanup
* Run drush en hdbt_default 
* Run make drush-cr

#### How to test

* Check the theme's modules/hdbt_default/src/entity folder.
  * Test all the matching paragraphs by adding them to a page.

2023-07-25 10:43 UTC, jeremysteerio requested changes
When adding media paragraphs (map or video embeds) I'm getting the following error: 
```
InvalidArgumentException: The URI '' is invalid. You must use a valid URI scheme. in Drupal\Core\Url::fromUri() (line 293 of core/lib/Drupal/Core/Url.php).
```

Seems that during render, something calls `public/core/lib/Drupal/Core/Template/TwigExtension::getLink` without valid url

2023-07-25 10:43 UTC, jeremysteerio commented on hdbt.theme
> -  $variables['theme_path'] = _hdbt_get_theme_path();
This function still gets called on lines 69 and 180 of `hdbt.theme` resulting in errors

2023-07-25 10:43 UTC, jeremysteerio commented on hdbt.theme
>      $search_urls = hdbt_get_global_url($variables['current_langcode']);
Since `hdbt_preprocess` has been removed, current langcode does not get added into `$variables`, making calls to `hdbt_get_global_url` fail

2023-08-28 07:25 UTC, tuutti requested changes
We should change `drupal/helfi_platform_config` conflict version (in https://github.com/City-of-Helsinki/drupal-hdbt/blob/main/composer.json#L12) to match the the latest platform config version once https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/567 is merged

2023-08-31 05:22 UTC, tuutti approved these changes

2023-09-04 04:55 UTC, merged