UHF-8719 Service channel changes
City-of-Helsinki/drupal-hdbt pull request #752
Opened 2023-08-23 12:04 UTC by teroelonen

# [UHF-8719](https://helsinkisolutionoffice.atlassian.net/browse/UHF-8719)

## What was done

* Added new icon for printable forms.
* Added new service_channel_type_verb that is based on the service channel type and is printed on the service channel instead of the regular name.
*  Added two nasty conditions for the phone charge info value and the availability summary value that make it possible to print something else that the API outputs.
* Added prefix for telephone service channels phone number.
* Added new template suggestion for service channel fields so that the fields can be targeted based on their parents type.
* Added template for eservice field links that prints out button whereas other links are printed out as normal links.
* Styled the service channels to match given layouts and changed the html dom to make the layouts possible.
* Added translations for new strings.

## How to install

* Make sure your instance is up and running on latest dev branch. You need to test this with at least two instances: SOTE and some other that has TPR enabled.
  * If you are testing SOTE:
    * `git fetch`
    * `git checkout UHF-8719_service_channel_changes`
    * `make fresh`
  * If you are testing some other instance:
    * `git pull origin dev`
    * `make fresh`
* Update the HDBT theme
  * `composer require drupal/hdbt:dev-UHF-8719_service_channel_changes`
* Update the helfi_tpr module
  * `composer require drupal/helfi_tpr:dev-UHF-8719`
* Run `make drush-cr`
* Go to shell `make shell` and run `drush locale:check; drush locale:update; drush cr` to import translations.

## How to test

* [x] Find a TPR unit with service channels such as the ones listed below. The types are listed after the links so that you can make sure to check all types of channels. Compare the service channel layout to the layout here: [https://www.figma.com/file/ZKi4C7RaTaNk991EL1whE3/Hel.fi-Komponentit?node-id=1216%3A109306&mode=dev](https://www.figma.com/file/ZKi4C7RaTaNk991EL1whE3/Hel.fi-Komponentit?node-id=1216%3A109306&mode=dev).
* [x] Make sure that the title of the card (depending on card type) is changed to verb form and is something in the lines of "Call" or "Send email".
* [x] Make sure the cards have all translations so that there is no English on Finnish or Swedish cards.
* [x] Make sure that for the telephone service phone charge field the value "pvm/mpm" is replaced with "Normaali puhelumaksu" string that is translated to all languages.
* [x] Make sure there is the verb Call as a prefix on the telephone service channels phone number now.
* [x] Make sure there is icons after the telephone, email and fillable form links on service channels.
* [x] SOTE: Check that the text that tells the user that the link on eservice requires authentication and that the link opens in a new tab is written on the same line. This can be found for example here: [https://helfi-sote.docker.so/fi/sosiaali-ja-terveyspalvelut/terveydenhoito/terveysasemat/koronarokotukset](https://helfi-sote.docker.so/fi/sosiaali-ja-terveyspalvelut/terveydenhoito/terveysasemat/koronarokotukset).
* [x] Check that the terms are correct and translated correctly. You can check the specs from the ticket since there is quite a lot of them: [https://helsinkisolutionoffice.atlassian.net/browse/UHF-8719](https://helsinkisolutionoffice.atlassian.net/browse/UHF-8719)
* [ ] Check that code follows our standards

## Channels for testing
* [https://helfi-kymp.docker.so/fi/kaupunkiymparisto-ja-liikenne/pysakointi/pysakoinninvalvonta](https://helfi-kymp.docker.so/fi/kaupunkiymparisto-ja-liikenne/pysakointi/pysakoinninvalvonta) ESERVICE, TELEPHONE, PRITABLE-FORM
* [https://helfi-sote.docker.so/fi/sosiaali-ja-terveyspalvelut/senioripalvelut/kotihoito/kotihoito-tukee-kotona-asumista](https://helfi-sote.docker.so/fi/sosiaali-ja-terveyspalvelut/senioripalvelut/kotihoito/kotihoito-tukee-kotona-asumista) ESERVICE, CHAT, EMAIL, TELEPHONE
* [https://helfi-kymp.docker.so/fi/kaupunkiymparisto-ja-liikenne/tontit-ja-rakentamisen-luvat/rakentamisvaiheen-ohjeet/maastoonmerkinta-ja-katselmukset](https://helfi-kymp.docker.so/fi/kaupunkiymparisto-ja-liikenne/tontit-ja-rakentamisen-luvat/rakentamisvaiheen-ohjeet/maastoonmerkinta-ja-katselmukset) EMAIL, TELEPHONE, WEBPAGE
* https://helfi-kymp.docker.so/fi/kaupunkiymparisto-ja-liikenne/ympariston-ja-luonnon-suojelu/elaimet/elainten-suojelu-ja-terveys/elainlaakaripalvelut TELEPHONE, LOCAL
* [https://helfi-sote.docker.so/fi/sosiaali-ja-terveyspalvelut/lasten-ja-perheiden-palvelut/lastensuojelu/lastensuojelun-asiakkaana/tukiperhetoiminta](https://helfi-sote.docker.so/fi/sosiaali-ja-terveyspalvelut/lasten-ja-perheiden-palvelut/lastensuojelu/lastensuojelun-asiakkaana/tukiperhetoiminta) EMAIL, TELEPHONE, MAIL

## Designers review

* [x] This PR has been visually reviewed by a designer (Sami Haikonen)

## Other PRs

* https://github.com/City-of-Helsinki/drupal-hdbt/pull/752
* https://github.com/City-of-Helsinki/drupal-helfi-sote/pull/630
* https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/152

[UHF-8719]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-08-29 08:12 UTC, tuutti requested changes

2023-08-29 08:12 UTC, tuutti commented on hdbt.theme
> +    $channel = Channel::load($channel['target_id']);
These changes should be moved here https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/blob/main/src/Entity/ChannelType.php if possible

2023-08-29 08:12 UTC, tuutti commented on translations/fi.po
> +
Some of these can be moved here https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/tree/main/translations

2023-08-29 08:12 UTC, tuutti commented on translations/sv.po
> +msgid "Use the online service"
Some of these can be moved here https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/tree/main/translations

2023-08-31 10:04 UTC, rpnykanen approved these changes

2023-08-31 12:20 UTC, tuutti approved these changes

2023-09-01 12:09 UTC, merged